### ISSUE TITLE
Wrong link for Labels

### ISSUE THREAD

**Issue by carlosdelsol** [axa-group/web-toolkit#84]
![lables](https://cloud.githubusercontent.com/assets/6344173/20758062/e272152e-b718-11e6-89eb-8e3444a8f8d2.png)

**Comment by FKSI** [comment]
Nice catch 👍

**Comment by davidknezic** [comment]
Oh wow! Crazy how did you find this? 😄

**Comment by carlosdelsol** [comment]
I was coding the Label component in [react-axa-ui](https://github.axa.com/web-guidelines/react-axa-ui) :mag: :yum:
